=== intel/gdb/gdb/features/gdb-target.dtd
<!-- Copyright (C) 2007-2026 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- The root element of a GDB target description is <target>.  -->

<!-- The osabi and compatible elements were added post GDB 6.8.  The version
     wasn't bumped, since older GDBs silently ignore unknown elements.  -->

<!ELEMENT target
	(architecture?, osabi?, compatible*, device?, feature*)>

<!ATTLIST target
	version		CDATA	#FIXED "1.0">

<!ELEMENT architecture	(#PCDATA)>

<!ELEMENT osabi	(#PCDATA)>

<!ELEMENT compatible	(#PCDATA)>

<!ELEMENT device	EMPTY>
<!ATTLIST device
	vendor-id	CDATA	#IMPLIED
	target-id	CDATA	#IMPLIED
	family		CDATA	#IMPLIED
	model		CDATA	#IMPLIED
	stepping	CDATA	#IMPLIED
	name		CDATA	#IMPLIED
	pci-slot	CDATA	#IMPLIED
	uuid		CDATA	#IMPLIED
	total-cores	CDATA	#IMPLIED
	total-threads	CDATA	#IMPLIED
	subdevice-id	CDATA	#IMPLIED
	>

<!ELEMENT feature
	((vector | flags | struct | union )*, reg*)>
<!ATTLIST feature
	name		ID	#REQUIRED>

<!ELEMENT reg		(description*)>
<!ATTLIST reg
	name		CDATA	#REQUIRED
	bitsize		CDATA	#REQUIRED
	regnum		CDATA	#IMPLIED
	save-restore	(yes | no) 'yes'
	expedited	(yes | no) #IMPLIED
	type		CDATA	'int'
	group		CDATA	#IMPLIED
	>

<!ELEMENT vector	EMPTY>
<!ATTLIST vector
	id		CDATA	#REQUIRED
	type		CDATA	#REQUIRED
	count		CDATA	#REQUIRED>

<!ELEMENT flags		(field+)>
<!ATTLIST flags
	id		CDATA	#REQUIRED
	size		CDATA	#REQUIRED>

<!ELEMENT enum		(evalue+)>
<!ATTLIST enum
	id		CDATA	#REQUIRED
	size		CDATA	#REQUIRED>

<!ELEMENT struct	(field+)>
<!ATTLIST struct
	id		CDATA	#REQUIRED
	size		CDATA	#IMPLIED>

<!ELEMENT union		(field+)>
<!ATTLIST union
	id		CDATA	#REQUIRED>

<!ELEMENT field		EMPTY>
<!ATTLIST field
	name		CDATA	#REQUIRED
	type		CDATA	#IMPLIED
	start		CDATA	#IMPLIED
	end		CDATA	#IMPLIED>

<!ELEMENT evalue	EMPTY>
<!ATTLIST evalue
	name		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

<!ENTITY % xinclude SYSTEM "xinclude.dtd">
%xinclude;

=== intel/gdb/gdb/features/i386/64bit-apx.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2024-2025 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.i386.apx">
  <reg name="r16" bitsize="64" type="int64"/>
  <reg name="r17" bitsize="64" type="int64"/>
  <reg name="r18" bitsize="64" type="int64"/>
  <reg name="r19" bitsize="64" type="int64"/>
  <reg name="r20" bitsize="64" type="int64"/>
  <reg name="r21" bitsize="64" type="int64"/>
  <reg name="r22" bitsize="64" type="int64"/>
  <reg name="r23" bitsize="64" type="int64"/>
  <reg name="r24" bitsize="64" type="int64"/>
  <reg name="r25" bitsize="64" type="int64"/>
  <reg name="r26" bitsize="64" type="int64"/>
  <reg name="r27" bitsize="64" type="int64"/>
  <reg name="r28" bitsize="64" type="int64"/>
  <reg name="r29" bitsize="64" type="int64"/>
  <reg name="r30" bitsize="64" type="int64"/>
  <reg name="r31" bitsize="64" type="int64"/>
</feature>

=== intel/gdb/gdb/features/intelgt-arf9.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2019-2021 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.intelgt.arf9">

  <reg name="a0"     bitsize="256" type="uint256"/>
  <reg name="acc0"   bitsize="256" type="uint256"/>
  <reg name="acc1"   bitsize="256" type="uint256"/>
  <reg name="acc2"   bitsize="256" type="uint256"/>
  <reg name="acc3"   bitsize="256" type="uint256"/>
  <reg name="acc4"   bitsize="256" type="uint256"/>
  <reg name="acc5"   bitsize="256" type="uint256"/>
  <reg name="acc6"   bitsize="256" type="uint256"/>
  <reg name="acc7"   bitsize="256" type="uint256"/>
  <reg name="acc8"   bitsize="256" type="uint256"/>
  <reg name="acc9"   bitsize="256" type="uint256"/>
  <reg name="f0"     bitsize="32"  type="uint32"/>
  <reg name="f1"     bitsize="32"  type="uint32"/>
  <!-- FIXME: BSpec says this is RO, should we still enable write
       to this reg? -->
  <reg name="ce"     bitsize="32"  type="uint32"/>
  <reg name="sp"     bitsize="128" type="uint128"/>
  <reg name="sr0"    bitsize="128" type="uint128"/>
  <!-- FIXME: only cr0.2 is available for edit,  do we really want
       to expose cr0? -->
  <reg name="cr0"    bitsize="128" type="uint128"/>
  <reg name="ip"     bitsize="32"  type="uint32"/>

  <reg name="tdr"    bitsize="128" type="uint128"/>

  <reg name="tm0"    bitsize="128" type="uint128"/>
  <reg name="emask"  bitsize="32"  type="uint32"/>
  <reg name="iemask" bitsize="32"  type="uint32"/>

  <reg name="mme0"   bitsize="256" type="uint256"/>
  <reg name="mme1"   bitsize="256" type="uint256"/>
  <reg name="mme2"   bitsize="256" type="uint256"/>
  <reg name="mme3"   bitsize="256" type="uint256"/>
  <reg name="mme4"   bitsize="256" type="uint256"/>
  <reg name="mme5"   bitsize="256" type="uint256"/>
  <reg name="mme6"   bitsize="256" type="uint256"/>
  <reg name="mme7"   bitsize="256" type="uint256"/>
</feature>

=== intel/gdb/gdb/features/i386/64bit-cet.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2013-2018 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.i386.cet">

  <struct id="cet_u_setting" size="8">
    <field name="SH_STK_EN" start="0" end="0" type="uint64"/>
    <field name="WR_SHSTK_EN" start="1" end="1" type="uint64"/>
    <field name="ENDBR_EN" start="2" end="2" type="uint64"/>
    <field name="LEG_IW_EN" start="3" end="3" type="uint64"/>
    <field name="NO_TRACK_EN" start="4" end="4" type="uint64"/>
    <field name="SUPPRESS_DIS" start="5" end="5" type="uint64"/>
    <field name="RSVD" start="6" end="9" type="uint64"/>
    <field name="SUPPRESS" start="10" end="10" type="uint64"/>
    <field name="TRACKER" start="11" end="11" type="uint64"/>
    <field name="EB_LEG_BITMAP_BASE" start="12" end="63" type="data_ptr"/>
  </struct>

  <reg name="cet_u" bitsize="64" type="cet_u_setting"/>
  <reg name="pl3_ssp" bitsize="64" type="code_ptr"/>

</feature>

=== intel/gdb/gdb/features/intelgt-grf.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2019-2021 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.intelgt.grf">

  <reg name="r0" bitsize="256" type="uint256"/>
  <reg name="r1" bitsize="256" type="uint256"/>
  <reg name="r2" bitsize="256" type="uint256"/>
  <reg name="r3" bitsize="256" type="uint256"/>
  <reg name="r4" bitsize="256" type="uint256"/>
  <reg name="r5" bitsize="256" type="uint256"/>
  <reg name="r6" bitsize="256" type="uint256"/>
  <reg name="r7" bitsize="256" type="uint256"/>
  <reg name="r8" bitsize="256" type="uint256"/>
  <reg name="r9" bitsize="256" type="uint256"/>
  <reg name="r10" bitsize="256" type="uint256"/>
  <reg name="r11" bitsize="256" type="uint256"/>
  <reg name="r12" bitsize="256" type="uint256"/>
  <reg name="r13" bitsize="256" type="uint256"/>
  <reg name="r14" bitsize="256" type="uint256"/>
  <reg name="r15" bitsize="256" type="uint256"/>
  <reg name="r16" bitsize="256" type="uint256"/>
  <reg name="r17" bitsize="256" type="uint256"/>
  <reg name="r18" bitsize="256" type="uint256"/>
  <reg name="r19" bitsize="256" type="uint256"/>
  <reg name="r20" bitsize="256" type="uint256"/>
  <reg name="r21" bitsize="256" type="uint256"/>
  <reg name="r22" bitsize="256" type="uint256"/>
  <reg name="r23" bitsize="256" type="uint256"/>
  <reg name="r24" bitsize="256" type="uint256"/>
  <reg name="r25" bitsize="256" type="uint256"/>
  <reg name="r26" bitsize="256" type="uint256"/>
  <reg name="r27" bitsize="256" type="uint256"/>
  <reg name="r28" bitsize="256" type="uint256"/>
  <reg name="r29" bitsize="256" type="uint256"/>
  <reg name="r30" bitsize="256" type="uint256"/>
  <reg name="r31" bitsize="256" type="uint256"/>
  <reg name="r32" bitsize="256" type="uint256"/>
  <reg name="r33" bitsize="256" type="uint256"/>
  <reg name="r34" bitsize="256" type="uint256"/>
  <reg name="r35" bitsize="256" type="uint256"/>
  <reg name="r36" bitsize="256" type="uint256"/>
  <reg name="r37" bitsize="256" type="uint256"/>
  <reg name="r38" bitsize="256" type="uint256"/>
  <reg name="r39" bitsize="256" type="uint256"/>
  <reg name="r40" bitsize="256" type="uint256"/>
  <reg name="r41" bitsize="256" type="uint256"/>
  <reg name="r42" bitsize="256" type="uint256"/>
  <reg name="r43" bitsize="256" type="uint256"/>
  <reg name="r44" bitsize="256" type="uint256"/>
  <reg name="r45" bitsize="256" type="uint256"/>
  <reg name="r46" bitsize="256" type="uint256"/>
  <reg name="r47" bitsize="256" type="uint256"/>
  <reg name="r48" bitsize="256" type="uint256"/>
  <reg name="r49" bitsize="256" type="uint256"/>
  <reg name="r50" bitsize="256" type="uint256"/>
  <reg name="r51" bitsize="256" type="uint256"/>
  <reg name="r52" bitsize="256" type="uint256"/>
  <reg name="r53" bitsize="256" type="uint256"/>
  <reg name="r54" bitsize="256" type="uint256"/>
  <reg name="r55" bitsize="256" type="uint256"/>
  <reg name="r56" bitsize="256" type="uint256"/>
  <reg name="r57" bitsize="256" type="uint256"/>
  <reg name="r58" bitsize="256" type="uint256"/>
  <reg name="r59" bitsize="256" type="uint256"/>
  <reg name="r60" bitsize="256" type="uint256"/>
  <reg name="r61" bitsize="256" type="uint256"/>
  <reg name="r62" bitsize="256" type="uint256"/>
  <reg name="r63" bitsize="256" type="uint256"/>
  <reg name="r64" bitsize="256" type="uint256"/>
  <reg name="r65" bitsize="256" type="uint256"/>
  <reg name="r66" bitsize="256" type="uint256"/>
  <reg name="r67" bitsize="256" type="uint256"/>
  <reg name="r68" bitsize="256" type="uint256"/>
  <reg name="r69" bitsize="256" type="uint256"/>
  <reg name="r70" bitsize="256" type="uint256"/>
  <reg name="r71" bitsize="256" type="uint256"/>
  <reg name="r72" bitsize="256" type="uint256"/>
  <reg name="r73" bitsize="256" type="uint256"/>
  <reg name="r74" bitsize="256" type="uint256"/>
  <reg name="r75" bitsize="256" type="uint256"/>
  <reg name="r76" bitsize="256" type="uint256"/>
  <reg name="r77" bitsize="256" type="uint256"/>
  <reg name="r78" bitsize="256" type="uint256"/>
  <reg name="r79" bitsize="256" type="uint256"/>
  <reg name="r80" bitsize="256" type="uint256"/>
  <reg name="r81" bitsize="256" type="uint256"/>
  <reg name="r82" bitsize="256" type="uint256"/>
  <reg name="r83" bitsize="256" type="uint256"/>
  <reg name="r84" bitsize="256" type="uint256"/>
  <reg name="r85" bitsize="256" type="uint256"/>
  <reg name="r86" bitsize="256" type="uint256"/>
  <reg name="r87" bitsize="256" type="uint256"/>
  <reg name="r88" bitsize="256" type="uint256"/>
  <reg name="r89" bitsize="256" type="uint256"/>
  <reg name="r90" bitsize="256" type="uint256"/>
  <reg name="r91" bitsize="256" type="uint256"/>
  <reg name="r92" bitsize="256" type="uint256"/>
  <reg name="r93" bitsize="256" type="uint256"/>
  <reg name="r94" bitsize="256" type="uint256"/>
  <reg name="r95" bitsize="256" type="uint256"/>
  <reg name="r96" bitsize="256" type="uint256"/>
  <reg name="r97" bitsize="256" type="uint256"/>
  <reg name="r98" bitsize="256" type="uint256"/>
  <reg name="r99" bitsize="256" type="uint256"/>
  <reg name="r100" bitsize="256" type="uint256"/>
  <reg name="r101" bitsize="256" type="uint256"/>
  <reg name="r102" bitsize="256" type="uint256"/>
  <reg name="r103" bitsize="256" type="uint256"/>
  <reg name="r104" bitsize="256" type="uint256"/>
  <reg name="r105" bitsize="256" type="uint256"/>
  <reg name="r106" bitsize="256" type="uint256"/>
  <reg name="r107" bitsize="256" type="uint256"/>
  <reg name="r108" bitsize="256" type="uint256"/>
  <reg name="r109" bitsize="256" type="uint256"/>
  <reg name="r110" bitsize="256" type="uint256"/>
  <reg name="r111" bitsize="256" type="uint256"/>
  <reg name="r112" bitsize="256" type="uint256"/>
  <reg name="r113" bitsize="256" type="uint256"/>
  <reg name="r114" bitsize="256" type="uint256"/>
  <reg name="r115" bitsize="256" type="uint256"/>
  <reg name="r116" bitsize="256" type="uint256"/>
  <reg name="r117" bitsize="256" type="uint256"/>
  <reg name="r118" bitsize="256" type="uint256"/>
  <reg name="r119" bitsize="256" type="uint256"/>
  <reg name="r120" bitsize="256" type="uint256"/>
  <reg name="r121" bitsize="256" type="uint256"/>
  <reg name="r122" bitsize="256" type="uint256"/>
  <reg name="r123" bitsize="256" type="uint256"/>
  <reg name="r124" bitsize="256" type="uint256"/>
  <reg name="r125" bitsize="256" type="uint256"/>
  <reg name="r126" bitsize="256" type="uint256"/>
  <reg name="r127" bitsize="256" type="uint256"/>

</feature>

=== intel/gdb/gdb/features/i386/64bit-amx.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2020-2022 Free Software Foundation, Inc.
   Copyright (C) 2025-2026 Intel Corporation

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.i386.amx">
  <vector id="v_i8" type="int8" count="64"/>
  <vector id="matrix_i8" type="v_i8" count="128"/>

  <vector id="v_ui8" type="uint8" count="64"/>
  <vector id="matrix_ui8" type="v_ui8" count="128"/>

  <vector id="v_i32" type="int32" count="16"/>
  <vector id="matrix_i32" type="v_i32" count="128"/>

  <vector id="v_bf16" type="bfloat16" count="32"/>
  <vector id="matrix_bf16" type="v_bf16" count="128"/>

  <vector id="v_fp16" type="ieee_half" count="32"/>
  <vector id="matrix_fp16" type="v_fp16" count="128"/>

  <vector id="v_fp32" type="ieee_single" count="16"/>
  <vector id="matrix_fp32" type="v_fp32" count="128"/>

  <union id="tiledata_type">
    <field name="m_int8" type="matrix_i8"/>
    <field name="m_uint8" type="matrix_ui8"/>
    <field name="m_int32" type="matrix_i32"/>
    <field name="m_bf16" type="matrix_bf16"/>
    <field name="m_fp16" type="matrix_fp16"/>
    <field name="m_fp32" type="matrix_fp32"/>
  </union>

  <!-- For tilecfg_raw, we choose an arbitrary type that has the size
       of 512 bits.  -->
  <reg name="tilecfg_raw" bitsize="512" type="v_i8"/>

  <reg name="tiledata" bitsize="65536" type="tiledata_type"/>
</feature>

=== intel/gdb/gdb/features/nios2-cpu.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2012-2025 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.nios2.cpu">
  <reg name="zero" bitsize="32" type="uint32"/>
  <reg name="at" bitsize="32" type="uint32"/>
  <reg name="r2" bitsize="32" type="uint32"/>
  <reg name="r3" bitsize="32" type="uint32"/>
  <reg name="r4" bitsize="32" type="uint32"/>
  <reg name="r5" bitsize="32" type="uint32"/>
  <reg name="r6" bitsize="32" type="uint32"/>
  <reg name="r7" bitsize="32" type="uint32"/>
  <reg name="r8" bitsize="32" type="uint32"/>
  <reg name="r9" bitsize="32" type="uint32"/>
  <reg name="r10" bitsize="32" type="uint32"/>
  <reg name="r11" bitsize="32" type="uint32"/>
  <reg name="r12" bitsize="32" type="uint32"/>
  <reg name="r13" bitsize="32" type="uint32"/>
  <reg name="r14" bitsize="32" type="uint32"/>
  <reg name="r15" bitsize="32" type="uint32"/>
  <reg name="r16" bitsize="32" type="uint32"/>
  <reg name="r17" bitsize="32" type="uint32"/>
  <reg name="r18" bitsize="32" type="uint32"/>
  <reg name="r19" bitsize="32" type="uint32"/>
  <reg name="r20" bitsize="32" type="uint32"/>
  <reg name="r21" bitsize="32" type="uint32"/>
  <reg name="r22" bitsize="32" type="uint32"/>
  <reg name="r23" bitsize="32" type="uint32"/>
  <reg name="et" bitsize="32" type="uint32"/>
  <reg name="bt" bitsize="32" type="uint32"/>
  <reg name="gp" bitsize="32" type="data_ptr"/>
  <reg name="sp" bitsize="32" type="data_ptr"/>
  <reg name="fp" bitsize="32" type="data_ptr"/>
  <reg name="ea" bitsize="32" type="code_ptr"/>
  <reg name="sstatus" bitsize="32" type="uint32"/>
  <reg name="ra" bitsize="32" type="code_ptr"/>
  <reg name="pc" bitsize="32" type="code_ptr"/>
  <reg name="status" bitsize="32" type="uint32"/>
  <reg name="estatus" bitsize="32" type="uint32"/>
  <reg name="bstatus" bitsize="32" type="uint32"/>
  <reg name="ienable" bitsize="32" type="uint32"/>
  <reg name="ipending" bitsize="32" type="uint32"/>
  <reg name="cpuid" bitsize="32" type="uint32"/>
  <reg name="ctl6" bitsize="32" type="uint32"/>
  <reg name="exception" bitsize="32" type="uint32"/>
  <reg name="pteaddr" bitsize="32" type="uint32"/>
  <reg name="tlbacc" bitsize="32" type="uint32"/>
  <reg name="tlbmisc" bitsize="32" type="uint32"/>
  <reg name="eccinj" bitsize="32" type="uint32"/>
  <reg name="badaddr" bitsize="32" type="uint32"/>
  <reg name="config" bitsize="32" type="uint32"/>
  <reg name="mpubase" bitsize="32" type="uint32"/>
  <reg name="mpuacc" bitsize="32" type="uint32"/>
</feature>

=== intel/gdb/gdb/features/intelgt-debug.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2019-2021 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- Virtual debug registers.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.intelgt.debug">

  <reg name="emask"  bitsize="32"  type="uint32"/>
  <reg name="iemask" bitsize="32"  type="uint32"/>
  <reg name="btbase" bitsize="64" type="uint64"/>
  <reg name="scrbase" bitsize="64" type="uint64"/>
  <reg name="genstbase" bitsize="64" type="uint64"/>
  <reg name="sustbase" bitsize="64" type="uint64"/>
  <reg name="blsustbase" bitsize="64" type="uint64"/>
  <reg name="blsastbase" bitsize="64" type="uint64"/>
  <reg name="isabase" bitsize="64" type="uint64"/>
  <reg name="iobase" bitsize="64" type="uint64"/>
  <reg name="dynbase" bitsize="64" type="uint64"/>

</feature>
